

insert into author (cod_author, full_name, sex, born_date, country, bio) values
(default,'J.K. Rowling','man','3-21-1997','usa','nothing to declare'),
(default,'Douglas Adams','man','10-31-2007','usa','nothing to declare'),
(default,'J.R.R. Tolkien','man','12-23-2020','Ecuador','nothing to declare'),
(default,'Chris Smith','woman','7-31-1986','Iceland','nothing to declare'),
(default,'Jude Fisher','woman','1-17-2020','Comoros','nothing to declare'),
(default,'Dave Thomas','man','6-21-2013','Andorra','nothing to declare'),
(default,'Gary Paulsen','man','12-17-1992','Netherlands Antilles','nothing to declare'),
(default,'Donna Ickes','woman','5-16-2000','Suriname','nothing to declare'),
(default,'Molly Hatchet','woman','5-16-2004','Estonia','nothing to declare'),
(default,'Dale Peck','man','01-13-1987','Canada','nothing to declare'),
(default,'Angela Knight','woman','4-20-2006','New Caledonia','nothing to declare'),
(default,'Patricia A. McKillip','woman','3-16-2009','Liberia','nothing to declare'),
(default,'Philippa Carr','woman','9-22-1999','Vanuatu','nothing to declare'),
(default,'Edward P. Jones','man','1-19-2005','Senegal','nothing to declare'),
(default,'Satyajit Das','man','7-14-1997','Wallis and Futuna','nothing to declare'),
(default,'Mark Smylie','man','7-18-1982','Zambia','nothing to declare'),
(default,'Heidi Hayes Jacobs','woman','9-15-2003','Latvia','nothing to declare'),
(default,'Heidi Baker','woman','2-26-2019','Suriname','nothing to declare'),
(default,'Rolland Baker','man','7-19-1988','Lesotho','nothing to declare'),
(default,'Heidi Fleiss','woman','2-13-1988','Isle of Man','nothing to declare'),
(default,'Bryce Courtenay','man','10-23-2012','Kenya','nothing to declare'),
(default,'John C. Maxwell','man','11-29-1993','Morocco','nothing to declare'),
(default,'Dave Lakhani','man','8-25-1988','','nothing to declare'),
(default,'Chris Malta','man','11-24-2004','Montenegro','nothing to declare'),
(default,'Julia Wilkinson','woman','7-31-1988','Slovakia','nothing to declare'),
(default,'Rob Orsini','man','6-28-2009','British Virgin Islands','nothing to declare'),
(default,'Leo Tolstoy','man','7-26-1995','Angola','nothing to declare'),
(default,'Gloria Goldreich','woman','5-18-1998','Eritrea','nothing to declare'),
(default,'Mulk Raj Anand','man','6-24-2021','Comoros','nothing to declare'),
(default,'John Banville','man','4-25-2004','Togo','nothing to declare'),
(default,'V.T. Rajshekar','man','2-14-2005','Congo - Brazzaville','nothing to declare'),
(default,'Barry R. Cournoyer','man','10-22-2007','Mauritius','nothing to declare'),
(default,'George Smoot','man','4-26-2000','Bahamas','nothing to declare'),
(default,'Cynthia Harrod-Eagles','woman','3-31-2008','Syria','nothing to declare'),
(default,'Ewan McGregor','man','7-27-1998','Micronesia','nothing to declare'),
(default,'Daniel Abraham','man','1-19-1982','Togo','nothing to declare'),
(default,'Charles Willeford','man','6-19-2004','India','nothing to declare'),
(default,'Tom Wolfe','man','4-15-2012','Cyprus','nothing to declare'),
(default,'Quentin Blake','man','2-13-1986','Uganda','nothing to declare'),
(default,'Henry Miller','man','9-27-2006','','nothing to declare'),
(default,'Henry James','man','9-18-2009','Russia','nothing to declare'),
(default,'Marguerite Duras','woman','2-23-1983','United Arab Emirates','nothing to declare'),
(default,'Kahlil Gibran','man','9-15-2005','Ecuador','nothing to declare'),
(default,'Deidre S. Laiken','woman','3-14-1980','Malta','nothing to declare'),
(default,'Ralph Ginzburg','man','7-23-2004','Wake Island','nothing to declare'),
(default,'Gabriel GarcA­a MA¡rquez','man','4-18-1981','','nothing to declare'),
(default,'Dr. Seuss','man','1-31-2018','Tajikistan','nothing to declare'),
(default,'Debbie Raleigh','woman','11-15-2007','Morocco','nothing to declare'),
(default,'Kevin Henkes','man','12-13-1992','North Vietnam','nothing to declare'),
(default,'Patrick SA¼skind','man','1-21-1997','China','nothing to declare'),
(default,'Nick Webb','man','8-27-2014','Venezuela','nothing to declare'),
(default,'Terry Jones','man','10-29-2020','Nauru','nothing to declare'),
(default,'Nick Flynn','man','10-16-2004','Macedonia','nothing to declare'),
(default,'Thomas Pynchon','man','6-17-2021','Saint Martin','nothing to declare'),
(default,'Jared Diamond','man','10-13-1981','Zimbabwe','nothing to declare'),
(default,'Stephen Leeb','man','10-27-1994','Austria','nothing to declare'),
(default,'Robert D. Putnam','woman','10-28-1987','Jersey','nothing to declare'),
(default,'Philip K. Howard','man','2-23-2003','Guatemala','nothing to declare'),
(default,'Joy Harjo','man','2-17-1994','Union of Soviet Socialist Republics','nothing to declare'),
(default,'Marc J. Seifer','woman','4-30-2004','Wallis and Futuna','nothing to declare'),
(default,'Carol Dommermuth-Costa','man','3-22-1989','Serbia and Montenegro','nothing to declare'),
(default,'Julie Elizabeth Leto','woman','1-21-1981','Wake Island','nothing to declare'),
(default,'William Golding','woman','9-30-1985','Western Sahara','nothing to declare'),
(default,'Victor Davis Hanson','woman','12-13-1993','Georgia','nothing to declare'),
(default,'Ephraim Sevela','woman','1-28-2021','Vanuatu','nothing to declare'),
(default,'Alice Sebold','woman','2-19-2002','American Samoa','nothing to declare'),
(default,'Sharyn McCrumb','man','9-17-1984','Guam','nothing to declare'),
(default,'Dave Shea','man','11-15-1991','Sri Lanka','nothing to declare'),
(default,'Michael Ochs','man','3-23-1995','Colombia','nothing to declare'),
(default,'Chuck Klosterman','woman','10-17-2011','Belgium','nothing to declare'),
(default,'Jane Feather','woman','11-29-1980','Maldives','nothing to declare'),
(default,'Catharine M. Fishel','woman','4-16-1998','Brazil','nothing to declare'),
(default,'Colin Wells','man','2-24-2004','Jordan','nothing to declare'),
(default,'Billy Collins','man','3-22-1986','Wake Island','nothing to declare'),
(default,'Kevin Trudeau','man','11-20-1980','usa','nothing to declare'),
(default,'Bernard Malamud','man','7-14-1981','usa','nothing to declare'),
(default,'Brian Greene','man','10-26-1982','Canada','nothing to declare'),
(default,'Upasika Kee Nanayon','woman','2-17-1994','Canada','nothing to declare'),
(default,'Rob Humphreys','man','7-13-2015','uk','nothing to declare'),
(default,'H.G. Bissinger','woman','12-22-2005','uk','nothing to declare'),
(default,'Neal Stephenson','woman','11-21-2012','uk','nothing to declare'),
(default,'Dan Harrington','man','3-14-1998','uk','nothing to declare'),
(default,'Paulo Coelho','man','10-22-2016','usa','nothing to declare'),
(default,'Hiromu Arakawa','man','12-29-2001','usa','nothing to declare'),
(default,'Robert Harris','man','10-18-2007','usa','nothing to declare'),
(default,'John Steinbeck','man','7-26-1989','usa','nothing to declare'),
(default,'Neil Strauss','man','6-22-2005','usa','nothing to declare'),
(default,'Ellen Raskin','man','7-20-1997','Canada','nothing to declare'),
(default,'David James','woman','3-16-1988','uk','nothing to declare'),
(default,'Mineko Iwasaki','woman','8-27-1980','uk','nothing to declare'),
(default,'J. Torres','man','5-20-2008','uk','nothing to declare'),
(default,'Margaret Johnson','man','6-21-1995','uk','nothing to declare'),
(default,'Dan Brown','man','3-18-1992','uk','nothing to declare'),
(default,'P.J. Parrish','man','4-29-2010','usa','nothing to declare'),
(default,'Napoleon Hill','man','11-16-2005','usa','nothing to declare'),
(default,'Mike Mason','man','11-30-1985','usa','nothing to declare'),
(default,'Riki Anne Wilchins','man','12-20-1989','usa','nothing to declare'),
(default,'Donald J. Trump','woman','5-18-1999','usa','nothing to declare'),
(default,'George S. Clason','man','6-19-2010','Canada','nothing to declare'),
(default,'Trevanian','man','1-18-2011','Canada','nothing to declare'),
(default,'David McCullough','woman','8-14-1989','uk','nothing to declare'),
(default,'Peter Stone','man','8-22-2021','uk','nothing to declare'),
(default,'Eric Schlosser','man','3-16-1991','uk','nothing to declare'),
(default,'Lisa See','man','3-14-2012','usa','nothing to declare'),
(default,'John Grisham','man','4-17-2002','usa','nothing to declare'),
(default,'Stephen W. Frey','man','11-20-2004','Latvia','nothing to declare'),
(default,'Bill Phillips','woman','12-20-1983','Lebanon','nothing to declare'),
(default,'Robert G. Hagstrom','man','2-13-2015','Tajikistan','nothing to declare'),
(default,'Robert P. Miles','man','11-20-2018','Lesotho','nothing to declare'),
(default,'Barbara Park','man','8-28-2001','Isle of Man','nothing to declare'),
(default,'Sarah Mlynowski','man','4-22-1987','Australia','nothing to declare'),
(default,'Frank McConnell','man','11-13-2019','Kenya','nothing to declare'),
(default,'Ursula Ferrigno','man','6-25-2014','Kenya','nothing to declare'),
(default,'Giada De Laurentiis','man','6-25-1987','Morocco','nothing to declare'),
(default,'Tyler Florence','man','6-29-2011','','nothing to declare'),
(default,'Steven D. Levitt','man','2-28-2018','Faroe Islands','nothing to declare'),
(default,'Barry Eisler','woman','8-25-1988','','nothing to declare'),
(default,'Robert Templer','man','1-28-1983','Montenegro','nothing to declare'),
(default,'James Frey','man','4-22-2015','Slovakia','nothing to declare'),
(default,'Python Bonkers','woman','4-23-2002','Lithuania','nothing to declare'),
(default,'James Pinocchio','woman','6-22-2000','Eritrea','nothing to declare'),
(default,'James M. Kouzes','man','11-14-1998','British Virgin Islands','nothing to declare'),
(default,'Gary Yukl','woman','8-25-1983','Kazakhstan','nothing to declare'),
(default,'Rudolph W. Giuliani','woman','10-19-1991','Eritrea','nothing to declare'),
(default,'Jean M. Auel','woman','3-27-1997','usa','nothing to declare'),
(default,'Steven Pressfield','man','11-20-1985','usa','nothing to declare'),
(default,'Stephen J. Rosen','woman','2-17-1989','','nothing to declare'),
(default,'Plato','woman','6-24-2012','usa','nothing to declare'),
(default,'Josef Pieper','woman','1-24-1991','usa','nothing to declare'),
(default,'Herodotus','man','11-29-1992','usa','nothing to declare'),
(default,'Homer','woman','5-23-1986','usa','nothing to declare'),
(default,'Ed Roberson','man','12-29-2001','Argentina','nothing to declare'),
(default,'Carla Lynn Stockton','man','5-31-1992','usa','nothing to declare'),
(default,'Giorgio De Santillana','man','2-21-1991','usa','nothing to declare'),
(default,'Thucydides','man','12-24-2000','usa','nothing to declare'),
(default,'Cynthia W. Shelmerdine','man','1-29-1998','usa','nothing to declare'),
(default,'Euripides','woman','6-15-2008','usa','nothing to declare'),
(default,'Anne Carson','man','10-24-2002','usa','nothing to declare'),
(default,'Wole Soyinka','woman','6-16-2005','usa','nothing to declare'),
(default,'William Allan','man','6-24-1991','Canada','nothing to declare'),
(default,'Robert J. Milch','woman','5-14-2007','Canada','nothing to declare'),
(default,'Aeschylus','man','6-25-1986','uk','nothing to declare'),
(default,'Simon Goldhill','man','7-28-1996','uk','nothing to declare'),
(default,'Sophocles','woman','3-18-2008','uk','nothing to declare'),
(default,'Aristophanes','woman','11-21-1998','uk','nothing to declare'),
(default,'Mary GrandPrAc','man','1-19-2005','uk','nothing to declare'),
(default,'Alan Lee','man','10-18-1984','usa','nothing to declare'),
(default,'Christopher Lee','man','1-22-2019','usa','nothing to declare'),
(default,'David Heinemeier Hansson','man','7-23-1982','usa','nothing to declare'),
(default,'Edward Sciranko','man','3-26-2014','usa','nothing to declare'),
(default,'Sahara Kelly','woman','12-15-1998','usa','nothing to declare'),
(default,'Beverly Cleary','man','6-25-2000','','nothing to declare'),
(default,'Sharon Mazel','woman','8-28-2006','','nothing to declare'),
(default,'Lisa Suttora','man','5-23-2001','usa','nothing to declare'),
(default,'Richard Pevear','man','11-20-2008','usa','nothing to declare'),
(default,'David Magarshack','man','3-20-1998','usa','nothing to declare'),
(default,'Amy Mandelker','man','11-18-2008','usa','nothing to declare'),
(default,'Louise Maude','man','3-13-1992','Canada','nothing to declare'),
(default,'Y.N. Kly','woman','3-17-2006','uk','nothing to declare'),
(default,'Patty Carratello','man','2-21-2012','uk','nothing to declare'),
(default,'Keay Davidson','woman','11-13-2006','uk','nothing to declare'),
(default,'Charley Boorman','man','1-14-1992','usa','nothing to declare'),
(default,'James Lee Burke','man','8-21-2018','usa','nothing to declare'),
(default,'Lawrence Block','man','12-16-1993','usa','nothing to declare'),
(default,'Laura Huliska-Beith','man','1-14-1992','usa','nothing to declare'),
(default,'Thomas H. Moore','man','4-18-2001','usa','nothing to declare'),
(default,'Patricia Crick','man','12-20-1984','Mali','nothing to declare'),
(default,'Gabriel Brownstein','man','12-22-1988','Tonga','nothing to declare'),
(default,'Richard Seever','woman','4-19-2021','Saint Martin','nothing to declare'),
(default,'John Walbridge','man','9-17-1994','Tunisia','nothing to declare'),
(default,'Scott McKowen','man','2-18-2013','Christmas Island','nothing to declare'),
(default,'N.C. Wyeth','man','12-19-1997','Argentina','nothing to declare'),
(default,'Milo Winter','man','1-21-2022','Zimbabwe','nothing to declare'),
(default,'Christopher Cerf','man','4-24-1991','French Guiana','nothing to declare'),
(default,'Michael McCurdy','man','12-20-1998','Guatemala','nothing to declare'),
(default,'Christophe Claro','man','7-26-2001','Union of Soviet Socialist Republics','nothing to declare'),
(default,'John Leonard','man','11-18-2008','Sri Lanka','nothing to declare'),
(default,'David Thomson','man','4-28-2020','Wallis and Futuna','nothing to declare'),
(default,'Gloria Bird','man','10-24-1989','Western Sahara','nothing to declare'),
(default,'William H. Terbo','woman','6-15-1994','usa','nothing to declare'),
(default,'David Hatcher Childress','woman','11-27-1993','Canada','nothing to declare'),
(default,'Chad Fowler','woman','11-23-2019','jamaica','nothing to declare'),
(default,'CliffsNotes','woman','12-17-2018','mexico','nothing to declare'),
(default,'Antonina W. Bouis','woman','2-13-2019','mexico','nothing to declare'),
(default,'Molly E. Holzschlag','woman','9-27-2002','usa','nothing to declare'),
(default,'Carol Heyer','woman','10-22-2010','usa','nothing to declare'),
(default,'Thomas J. Steele','man','5-29-1986','usa','nothing to declare'),
(default,'Beth Chaplin','man','2-25-1982','Jersey','nothing to declare'),
(default,'Mark Honan','man','5-16-1984','Union of Soviet Socialist Republics','nothing to declare'),
(default,'Guy Abadia','woman','2-28-2014','Wake Island','nothing to declare'),
(default,'Bill Robertie','man','6-16-2007','Andorra','nothing to declare'),
(default,'Diane M. Hanson','woman','6-16-2002','Western Sahara','nothing to declare'),
(default,'Alan R. Clarke','man','2-24-1992','','nothing to declare'),
(default,'John Gregory Betancourt','man','2-29-2004','','nothing to declare'),
(default,'Peggy Mulloy','man','1-29-1998','','nothing to declare'),
(default,'Rande Brown','woman','9-18-1990','','nothing to declare'),
(default,'Philip Prowse','man','8-21-1996','','nothing to declare'),
(default,'Cindy Crawford','man','5-26-2015','usa','nothing to declare'),
(default,'Bill Miller','man','3-25-2007','usa','nothing to declare'),
(default,'Jason Lowe','man','12-17-2007','','nothing to declare'),
(default,'Victoria Pearson','man','4-16-1983','','nothing to declare'),
(default,'Petrina Tinslay','man','6-29-2009','usa','nothing to declare'),
(default,'Nicole Martel','man','3-16-1987','usa','nothing to declare'),
(default,'Barry Z. Posner','man','12-26-2015','usa','nothing to declare'),
(default,'David Copeland','man','12-15-2008','usa','nothing to declare'),
(default,'Walter Hamilton','woman','10-30-1990','uk','nothing to declare'),
(default,'C.J. Rowe','man','1-22-1996','uk','nothing to declare'),
(default,'Benjamin Jowett','man','1-28-2009','uk','nothing to declare'),
(default,'C.D.C. Reeve','man','8-27-2002','usa','nothing to declare'),
(default,'James H. Nichols Jr.','man','7-19-2017','usa','nothing to declare'),
(default,'Aubrey de SAclincourt','man','2-20-1982','usa','nothing to declare'),
(default,'Henry Francis Cary','man','1-14-1980','usa','nothing to declare'),
(default,'Edward Henry Blakeney','man','3-13-1987','Mali','nothing to declare'),
(default,'Peter Grene','man','1-14-1992','Tonga','nothing to declare'),
(default,'Robert Fagles','man','11-28-2014','North Korea','nothing to declare'),
(default,'Stanley Lombardo','man','10-13-2014','Saint Martin','nothing to declare'),
(default,'Robert Fitzgerald','man','7-25-1993','France','nothing to declare'),
(default,'W.H.D. Rouse','man','11-25-2004','Christmas Island','nothing to declare'),
(default,'Richmond Lattimore','no binary','4-29-2014','Zimbabwe','nothing to declare'),
(default,'Barbara Weiden Boyd','undefined','10-19-2008','Austria','nothing to declare'),
(default,'Henry Rushton Fairclough','man trans','5-22-1981','French Guiana','nothing to declare'),
(default,'Cecil Day-Lewis','man trans','9-23-2005','Jersey','nothing to declare'),
(default,'Stephen Orgel','undefined','10-25-1999','Guatemala','nothing to declare'),
(default,'Harold Bloom','man','3-19-1988','Union of Soviet Socialist Republics','nothing to declare'),
(default,'Adam Long','man','8-30-1996','Sri Lanka','nothing to declare'),
(default,'Clifford E. Landers','woman trans','3-21-2003','Serbia and Montenegro','nothing to declare'),
(default,'C.F. Smith','man','7-27-2007','usa','nothing to declare'),
(default,'Paul Woodruff','man','1-29-1994','usa','nothing to declare'),
(default,'Steven Lattimore','man','3-27-1988','usa','nothing to declare'),
(default,'David Kovacs','man','11-25-2012','usa','nothing to declare'),
(default,'Donald J. Mastronarde','man','4-30-1983','usa','nothing to declare'),
(default,'David Thompson','woman','1-17-2008','usa','nothing to declare'),
(default,'James Morwood','man','10-18-2020','usa','nothing to declare'),
(default,'Alan Shapiro','woman','11-27-1987','Canada','nothing to declare'),
(default,'E.D.A. Morshead','man','3-14-2010','uk','nothing to declare'),
(default,'Paul Roche','woman','2-20-2005','usa','nothing to declare'),
(default,'Edith Hall','woman','11-21-2012','usa','nothing to declare'),
(default,'J.E. Thomas','woman','3-29-2009','usa','nothing to declare'),
(default,'Roger D. Dawe','woman','5-27-2006','usa','nothing to declare'),
(default,'Jeffrey Henderson','woman','4-26-1982','Mali','nothing to declare'),
(default,'Leon Breedt','man','12-18-1980','North Korea','nothing to declare'),
(default,'Judy Mays','man','11-27-2006','France','nothing to declare'),
(default,'Larissa Volokhonsky','man','6-19-2001','Austria','nothing to declare'),
(default,'Theresa Wright','man','1-31-2010','Union of Soviet Socialist Republics','nothing to declare'),
(default,'Robert Uhlig','woman','1-23-1995','Sri Lanka','nothing to declare'),
(default,'Edward Mendelson','man','12-20-2003','Wallis and Futuna','nothing to declare'),
(default,'Salma H. Al-Kuzbari','woman','2-28-1986','','nothing to declare'),
(default,'Brice Matthieussent','man','2-17-2010','Wake Island','nothing to declare'),
(default,'Luc Sante','man','4-21-2000','','nothing to declare'),
(default,'Beth Cuthand','man','10-25-1987','Morocco','nothing to declare'),
(default,'Ulrike Wasel','woman','2-23-2017','Laos','nothing to declare'),
(default,'Alan Greenspan','man','2-19-2019','Nauru','nothing to declare'),
(default,'J.S. Bernstein','man','12-31-1980','Ethiopia','nothing to declare'),
(default,'Rebecca Morrill','woman','7-30-2002','Western Sahara','nothing to declare'),
(default,'Steve Fallon','woman','6-23-1989','Macedonia','nothing to declare'),
(default,'Tom Masters','woman','7-17-1986','Mali','nothing to declare'),
(default,'Stephen K. Ray','man','7-23-2016','North Korea','nothing to declare'),
(default,'A–zdemir Ance','man','7-27-2021','France','nothing to declare'),
(default,'MAbius','man','3-23-1986','Tunisia','nothing to declare'),
(default,'Rob Marshall','man','6-26-2021','Christmas Island','nothing to declare'),
(default,'Kenneth L. Fisher','man','4-25-2009','Argentina','nothing to declare'),
(default,'Maxine Clark','man','8-22-1984','usa','nothing to declare'),
(default,'Bill Bettencourt','man','1-24-1993','usa','nothing to declare'),
(default,'Emile Martel','woman','4-14-1983','usa','nothing to declare'),
(default,'Chris Emlyn-Jones','man','4-13-2014','usa','nothing to declare'),
(default,'John M. Marincola','woman','2-21-1992','usa','nothing to declare'),
(default,'Andrew Robert Burn','man','5-28-2018','usa','nothing to declare'),
(default,'George Rawlinson','man','2-15-2003','usa','nothing to declare'),
(default,'Andrew Ford','woman','3-24-2002','usa','nothing to declare'),
(default,'Peter Jones','man','2-19-1991','usa','nothing to declare'),
(default,'D.S. Carne-Ross','man','9-14-1995','Canada','nothing to declare'),
(default,'A.R. Braunmuller','man','5-17-2005','usa','nothing to declare'),
(default,'Rex Gibson','man','2-28-2001','usa','nothing to declare'),
(default,'Daniel Singer','woman','9-29-2018','usa','nothing to declare'),
(default,'KA¢muran Åžipal','man','11-24-1998','usa','nothing to declare'),
(default,'William Bedell Stanford','man','7-21-2014','usa','nothing to declare'),
(default,'Helene P. Foley','no binary','10-27-2020','usa','nothing to declare'),
(default,'Smith Palmer Bovie','woman trans','2-18-2013','usa','nothing to declare'),
(default,'Richard Seaford','man trans','7-16-2017','usa','nothing to declare'),
(default,'H.D.F. Kitto','woman trans','9-19-1995','Canada','nothing to declare'),
(default,'Mike Clark','no binary','5-27-2002','uk','nothing to declare'),
(default,'Sandee Hathaway','man trans','5-27-1985','uk','nothing to declare'),
(default,'John Bayley','no binary','5-18-1983','uk','nothing to declare'),
(default,'Valerie Martinez','no binary','11-19-1980','uk','nothing to declare'),
(default,'Bobby Flay','man trans','8-31-1990','usa','nothing to declare'),
(default,'Rosalind Thomas','','12-19-1980','usa','nothing to declare'),
(default,'Rex Warner','','4-29-1996','usa','nothing to declare'),
(default,'Seth Benardete','','2-28-1999','Canada','nothing to declare'),
(default,'Thomas Fuchs','','1-25-1993','uk','nothing to declare'),
(default,'Kate Douglas','','12-28-1992','uk','nothing to declare'),
(default,'Mark D. Widome','','12-20-1994','uk','nothing to declare'),
(default,'Patricia Blanco','','12-31-1985','uk','nothing to declare'),
(default,'Ralph Gladstone','','3-16-2000','uk','nothing to declare'),
(default,'Frank William Jones','','8-17-2007','iceland','nothing to declare'),
(default,'John Frederick Nims','','4-26-2020','iceland','nothing to declare'),
(default,'Michael Jameson','','12-25-2010','usa','nothing to declare');